name: Build and publish

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm 
        # https://pnpm.io/continuous-integration#github-actions
        uses: pnpm/action-setup@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Clean install dependencies
        run: pnpm install --frozen-lockfile
        # https://pnpm.io/cli/install#--frozen-lockfile

      - name: Build dist
        run: pnpm --filter @congruent-stack/congruent-api run build

      - name: Pnpm config for publishing
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          pnpm config set registry https://registry.npmjs.org/ --location=project
      
      - name: Publish monorepo package to npmjs registry
        run: pnpm publish --no-git-checks --access public

      - name: Publish packages to npmjs registry
        run: |
          pnpm --filter @congruent-stack/congruent-api publish --no-git-checks --access public